### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by PowerPress** [snowytoxa/selfhash#4]
Just found this and it looks awesome but how do I use it exactly? Do I need to have visual studio or anything to compile this and if so what? What are command arguments when you have it running?

**Comment by snowytoxa** [comment]
There is a build.bat file having a proper command line to build the thing with the visual studio.
There are no command line arguments to run it.

**Comment by johnjohnsp1** [comment]
using VStudio commandline 2019 actually but i think something is missing since i get this as output:

C:\temp\selfhash>build.bat
C:\temp\selfhash>cl server.cpp mysecurity.cpp /link Secur32.lib Advapi32.lib
Microsoft (R) C/C++ Optimizing Compiler Version 19.26.28805 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

server.cpp
server.cpp(5): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory
mysecurity.cpp
mysecurity.cpp(3): fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory
Generating Code...

C:\temp\selfhash>

even if i copy windows.h and stdlib.h from the C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0 
does not work, same errors.

anything i do wrong ?
thanks
